- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/Home.js
- frontend/src/Login.js
- frontend/src/Register.js
Started adding the react router and the initial login and register pages
https://phillyreads-hsrjpsbptp.now.sh
> Initial router setup 

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Navbar.js
- frontend/src/components/PReadsNavbar.js
- frontend/src/index.js
- frontend/src/pages/Home.js
- frontend/src/pages/KidsPage.js
- frontend/src/pages/ParentsPage.js
https://phillyreads-yorvrkuamu.now.sh
Related issues: #11 #12
> Add Bootstrap and convert the navbar to Bootstrap

- contributing.md
:rocket: Ready
Related issues: #18
> RFR Added branch file template contributing.md

- backend/api/views/authenticate.py
- backend/tests/test_basic.py
:rocket: Ready
This PR adds the functionality desired in issue 37. Tests were also changed to pass data to the endpoints through the regular application/json.
Related issues: #37
> RFR: Changed implementation of BE to not read from form data

- frontend/package-lock.json
- frontend/src/App.js
- frontend/src/components/Question.js
- frontend/src/components/QuestionList.js
- frontend/src/pages/TestPage.js
:rocket: Ready
https://phillyreads-mwfxrwpwrd.now.sh/questions
Do basic scaffolding of questionlist and question components and show an example of their use inside TestPage.js (Should eventually delete)
Related issues: #24
> RFR: Scaffolding QuestionList and Question Components

- frontend/src/App.js
- frontend/src/pages/Home.js
- frontend/src/pages/KidsPage.js
:rocket: Ready
Just doing some clean up work
Related issues: #8
> Fixed unused imports

- .github/pull_request_template.md
:rocket: Ready
Instructions on screenshots
> Add screenshot info for Linux/Window

- frontend/package.json
- frontend/src/components/Catalog.js
- frontend/src/components/CatalogCard.js
- frontend/src/pages/KidsPage.js
:rocket: Ready for Review
Created Catalog.js and CatalogCard.js file in the components folder 
Related issues: #15
> RFR: Create catalog component for content display

- backend/api/models/Book.py
- backend/api/models/Question.py
- backend/api/models/Quiz.py
- backend/api/models/__init__.py
- backend/api/views/main.py
:rocket: Ready
The models Question.py, Quiz.py, and Book.py have been defined.
Related issues: #30
> RFR: Added in basic scaffolding outline for models

- backend/.gitignore
:rocket: Ready
Git will not track vim swap files
Related issues: #45
> RFR: New BE .gitignore

- .circleci/config.yml
- backend/Pipfile
- backend/Pipfile.lock
- backend/tests/conftest.py
:rocket: Ready
Used the testing.postgresql package to spin up a postgresql testing fixture to be used in all tests. Changed circle ci tests to use postgresql too
Related issues: #49
> RFR: Changed SQLite tests to PostgreSQL tests

- backend/docker_recreate.sh
:rocket: Ready
Bash script that gets the id of the current postgres container, stops it, prunes system and volume information, and then recreates the postgres container
Run:
./docker_recreate
Related issues: #55
> RFR: Docker Script for recreating docker image with fresh postgres

- .circleci/config.yml
- backend/Pipfile
- backend/Pipfile.lock
- backend/tests/conftest.py
- schedule.md
:rocket: Ready
A rough overview of the production schedule for the next few weeks
Related issues: #52
> RFR: Production Schedule 

- frontend/package-lock.json
- frontend/src/components/CatalogCard.js
- frontend/src/components/Filter.js
- frontend/src/components/SearchBar.js
- frontend/src/components/SearchResults.js
- frontend/src/pages/KidsPage.js
- frontend/src/pages/Search.js
- frontend/src/utils/api.js
:construction: In development
Create a search page for books that returns results in catalog format
Related issues: #44 
> RFR: added Search.js page

- frontend/src/components/Catalog.js
- frontend/src/styles/Catalog.scss
🚀 Ready
- Centered pagination
- Added margins
Related issues: #41 
Before:
After:
> RFR: Add Catalog styling

- frontend/src/components/Question.js
- frontend/src/components/QuestionList.js
:rocket: Ready for Review!
https://phillyreads-xbkibmvzlc.now.sh
A Question component renders a singular question as one complete unit, composed of a title / numbering, options listed as clickable radio buttons, and a submit button that allows the user to see the correctness of their chosen answer.
Related issues: #25 
default: 
clicked answer w/o submission:
correct submitted answer:
incorrect submitted answer:
> RFR: Basic Question Interaction

- backend/api/models/QuestionResult.py
- backend/api/models/QuizResult.py
- backend/api/models/User.py
- backend/api/models/__init__.py
- backend/api/views/quiz.py
:rocket: Ready
This PR implements the POST /quiz_result.
Related issues: closes #76
> RFR: Implement POST /quiz_result

- backend/api/views/book.py
:rocket: Ready
Completed the year endpoint, just finds all distinct years where books exist and returns them in reverse sorted order
Related issues: closes #87
> RFR: Archive Year Endpoint

- backend/Pipfile.lock
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Filter.js
- frontend/src/components/SearchBar.js
- frontend/src/components/SearchResults.js
- frontend/src/pages/Search.js
- frontend/src/styles/Filter.scss
- frontend/src/styles/Search.scss
- frontend/src/utils/api.js
:rocket: Ready for review
https://phillyreads-ofxdizgmkh.now.sh 
Add ability to filter books from user search based on grade and year
Related issues: #66
> RFR: Add filtering books functionality

- frontend/src/App.js
- frontend/src/components/Catalog.js
- frontend/src/components/CatalogCardBook.js
- frontend/src/pages/ReadingOlympics/ROHome.js
- frontend/src/pages/ReadingOlympics/ROYearGradeView.js
- frontend/src/pages/ReadingOlympics/ROYearView.js
- frontend/src/styles/ReadingOlympics.scss
- frontend/src/utils/api.js
- frontend/src/utils/formatHelpers.js
:rocket: Ready
Will need to wait on BE endpoints, but please review code first
* `ROHome` at `/ReadingOlympics`: Main page for Reading Olympics. Has 2 main outgoing links: to current year's middle school book list, and to current year's intermediate book list
* `ROYearGradeView` at `/ReadingOlympics/:year/:grade`: View catalog of books for a specified year & grade
* `ROYearView` at `/ReadingOlympics/year/:year`: View catalog of books for a specified year
Related issues: Closes #60. Closes #70
> RFR: Reading Olympics Pages

- frontend/src/App.js
- frontend/src/components/Login.js
- frontend/src/components/PReadsNavbar.js
- frontend/src/pages/LoginPage.js
- frontend/src/pages/ParentsPage.js
- frontend/src/pages/ReadingOlympics/ROHome.js
- frontend/src/pages/ReadingOlympics/ROYearGradeView.js
- frontend/src/pages/ReadingOlympics/ROYearView.js
- frontend/src/pages/RegisterPage.js
:rocket: Ready
Boom 💢 
We no longer need to render a navbar in each individual page!
Related issues: Closes #59
> RFR: Extract navbar to be global

- backend/create_dummy_data.py
:rocket: Ready
Related issues: Fixes #97
> RFR: Fix script to match BE change

- backend/api/models/Book.py
:rocket: Ready
Related issues: fixes #100
> RFR: Adding book id to serialized book for /books endpoint

- frontend/src/pages/Home.js
- frontend/src/pages/ReadingOlympics/ROHome.js
- frontend/src/pages/Search.js
- frontend/src/styles/App.scss
- frontend/src/styles/Filter.scss
- frontend/src/styles/Home.scss
- frontend/src/styles/Login.scss
- frontend/src/styles/ReadingOlympics.scss
- frontend/src/styles/Search.scss
:rocket: Ready
More incremental styling changes
Related issues: #41 Closes #103
> RFR: Add page-specific classes to prevent styling bleed

- backend/Pipfile.lock
- backend/api/models/QuestionResult.py
- backend/api/models/QuizResult.py
- backend/api/models/User.py
- backend/api/models/__init__.py
- backend/api/views/quiz.py
:rocket: Ready
Created the following endpoints:
/{quiz_result_id}/question_results
/{user_id}/quiz_results 
Related issues: #77 #78
> RFR: User endpoints

- backend/api/models/Question.py
- backend/api/views/quiz.py
- backend/tests/test_quiz.py
:rocket: Ready
- Added it to `Question` model
- Modified create quiz endpoint to pass the needed param to the question constructor
- LMK if I missed anything
Related issues: Fixes #108
> RFR: Add correct_option to question model

- backend/create_dummy_data.py
:rocket: Ready
So far added in 5 intermediate and middle school books
- Going to add in atleast 1 quiz per book of around 3-4 questions?
- Maybe choose one book to have like 3 longer quizzes for a specific book
Edit: Added 3 quizzes to wishtree, i'd say lets go ahead and merge now just so we have some more quizzes and books to test with. Will continue adding data as necessary and as we go.
Related issues: fixes #105
> RFR: Adding in more dummy data

- frontend/src/components/Register.js
:rocket: Ready
https://phillyreads-wgbbthkerr.now.sh
Changed the redirect after register from `/kids` to `/`. 
Related issues: Fixes #113 
Before:
After:
> RFR: Changed redirect on register

- frontend/public/index.html
- frontend/src/components/Login.js
- frontend/src/components/Register.js
- frontend/src/components/SearchResults.js
- frontend/src/pages/Home.js
- frontend/src/pages/LoginPage.js
- frontend/src/pages/ParentsPage.js
- frontend/src/pages/ProfilePage.js
- frontend/src/pages/ReadingOlympics/ROYearGradeView.js
- frontend/src/pages/ReadingOlympics/ROYearView.js
- frontend/src/pages/RegisterPage.js
- frontend/src/pages/Search.js
- frontend/src/styles/App.scss
- frontend/src/styles/Catalog.scss
- frontend/src/styles/Home.scss
- frontend/src/styles/ParentsPage.scss
- frontend/src/styles/ReadingOlympics.scss
- frontend/src/styles/Search.scss
> Merge before MVP: Style tweaks

- schedule.md
> WIP Add tentative scheduling

- backend/docker_wipe.sh
:rocket: Ready
**./docker_wipe.sh** - will just clear the current running docker volume, wipe its data, and rerun it
**./docker_recreate.sh** - will do ./docker_wipe.sh and then run **pipenv run manage.py recreate_db**
Related issues: fixes #125
> RFR: Split docker scripts into two, docker recreate and docker wipe

- backend/api/views/authenticate.py
:rocket: Ready
Finished the User info route from swaggerhub to get name and email
Related issues: fixes #75
> RFR: User Info Route

- package-lock.json
🚀 
Related issues: #<number>
Related PRs: Fixes #135
> RFR: Delete package-lock.json from root directory

- frontend/src/components/Filter.js
- frontend/src/components/SearchResults.js
:construction: In development
got filters to change results but not completely accurate
Related issues: 66
> WIP: almost finished filtering functionality

- backend/api/views/book.py
:rocket: Ready
Related issues: closes #119
> RFR: Beginning of POST book_from_csv

- backend/api/models/User.py
- backend/api/views/authenticate.py
:rocket: Ready
Adds additional return fields to GET /user
Related issues: closes #162
> RFR: Exposed badge ids and is_admin through GET user endpoint

- backend/create_dummy_data.py
:rocket: Ready
Now when you run ./reset_db_with_sample_data.sh you will have one user ("david chang") that is already loaded as an admin
Related issues: closes #161
> RFR: Changed dummy data script to make David Chang an admin

- backend/api/core.py
- backend/api/views/authenticate.py
- backend/api/views/book.py
- backend/api/views/quiz.py
:rocket: Ready
POST /delete_quiz and POST /delete_book are now implemented. Two decorator functions have also bene written for routes: authenticated_route and admin_route.
Related issues: closes #165 and closes #168
> RFR:Delete a quiz/book

- backend/api/views/user.py
:rocket: Ready
Related issues: fixes #170
> RFR: User backend view import jwt hot fix

- backend/api/models/Book.py
- backend/api/views/book.py
- backend/api/views/quiz.py
- backend/create_dummy_data.py
:rocket: Ready
Made cover_url optional, perform the right validation on creating a book, and removed reader_url
Related issues: fixes #147, fixes #172
> RFR: Changed cover_url to optional, removed reader_url

- backend/api/models/Book.py
- backend/api/views/book.py
- backend/create_dummy_data.py
- backend/tests/test_quiz.py
:rocket: Ready
Upon request of philaREADS changed the book grade to not be 4/8 but middle/intermediate.
Related issues: closes #174
> RFR: Changed book grade to be middle or intermediate

- frontend/src/App.js
- frontend/src/pages/BookPage.js
- frontend/src/pages/NoMatchPage.js
- frontend/src/pages/QuizPage.js
:rocket: Ready
Related issues: Closes #181
> RFR: Rerouting / 404 not found

- frontend/src/components/Catalog.js
- frontend/src/components/QuizViewer.js
- frontend/src/styles/App.scss
:rocket: Ready
Adds a highlight to the current pagination page
> highlights current pagination page

- frontend/package.json
- frontend/src/components/Filter.js
- frontend/src/components/SearchBar.js
- frontend/src/components/SearchResults.js
- frontend/src/pages/Search.js
:rocket: Ready
Related issues: Closes #115
> RFR: Use search page query params to perform search

- frontend/src/components/Question.js
- frontend/src/components/QuizViewer.js
- frontend/src/styles/QuizPage.scss
:rocket: Ready
Added next button whenever you submit a question
> RFR: added next button whenever you submit a question

- frontend/src/components/QuizRedo.js
- frontend/src/components/QuizStart.js
- frontend/src/components/QuizViewer.js
- frontend/src/pages/QuizPage.js
:construction: In development
Related issues: Closes #26 
> click on finish attempt
> notification modal pops up
> you have the option to redo quiz or cancel out of the modal
>  click or x to close modal without doing anything to data
> click redo to redo quiz
> updates number of times quiz has been redone
> WIP: Redo Quiz

- backend/api/models/Quiz.py
- backend/api/models/QuizResult.py
- backend/api/models/User.py
- backend/api/views/book.py
- backend/api/views/quiz.py
- backend/create_dummy_data.py
- backend/tests/test_quiz.py
:rocket: Ready
Related issues: closes #164
> RFR: Edit quiz & WIP quiz

- frontend/src/components/AdminBookForm.js
- frontend/src/components/BookInfo.js
- frontend/src/components/CatalogCardBook.js
- frontend/src/components/QuizRedo.js
- frontend/src/pages/Home.js
- frontend/src/pages/ReadingOlympics/ROHome.js
- frontend/src/pages/ReadingOlympics/ROYearGradeView.js
- frontend/src/styles/BookInfo.scss
- frontend/src/styles/Home.scss
- frontend/src/utils/formatHelpers.js
:rocket: Ready after testing
Related issues: Closes #174
> RFR: Update FE to match grade datatype & book model changes

- backend/api/models/Book.py
- backend/api/views/book.py
- backend/tests/test_quiz.py
:rocket: Ready
Books have a published property. There is also now POST /publish_books
Related issues: closes #191
> RFR: finished book published property

- backend/create_dummy_data.py
:rocket: Ready
Added published: true to all book sample data items
Related issues: #193
> RFR: fix book publish property in sample data

- frontend/src/App.js
- frontend/src/pages/admin/AdminPage.js
- frontend/src/pages/protection/AdminProtection.js
- frontend/src/pages/protection/AuthenticatedProtection.js
:rocket: Ready
No joke, learning about this react children, higher order components and container components was fun
Related issues: Closes #157
> RFR: Add Admin & Authenticated route protection

- frontend/src/App.js
- frontend/src/components/AdminBookForm.js
- frontend/src/pages/Home.js
- frontend/src/pages/ReadingOlympics/ROHome.js
- frontend/src/pages/ReadingOlympics/RORedirectToCurrent.js
- frontend/src/utils/api.js
:rocket: Ready
- Redirecting -- `year/current` redirects to current year. `current/middle` and `current/intermediate` redirect to the appropriate years
- Bugfix: submitting an edit book form no longer gives error
> RFR: "current year" redirecting & bugfixes

- backend/api/views/book.py
- backend/api/views/quiz.py
- backend/api/views/user.py
- backend/create_dummy_data.py
- backend/tests/test_quiz.py
:rocket: Ready
:lock: 
Related issues: closes #194
> RFR: Added authentication to a lot of routes

- backend/api/views/book.py
:rocket: Ready
Had to do some digging but found a case insensitive contains basically for fuzzy searching
Related issues: fixes #102
> RFR: Backend GET /books Fuzzy Search

- backend/api/models/User.py
- backend/api/views/authenticate.py
- backend/api/views/quiz.py
- backend/api/views/user.py
- backend/create_dummy_data.py
- backend/tests/test_authenticate.py
- frontend/src/components/Login.js
- frontend/src/components/Register.js
- frontend/src/pages/AccountManagePage.js
🚀 rfr
- Changed user model to take in username instead of email
- Changed all endpoints to account for email/username change
- Changed login/register page to take in username instead of email
- Fixed update profile to work properly with revised endpoint
- Fixed successfully spelling error
Related issues: #84 #176
> RFR: email to username

- backend/api/views/quiz.py
:rocket: Ready
This removed all the appends that we thought were doing work but actually weren't. :lock: 
Related issues: closes #160
> RFR: Got rid of unnecesary appends

- frontend/src/components/Login.js
- frontend/src/components/PReadsNavbar.js
- frontend/src/components/Register.js
- frontend/src/pages/Home.js
:rocket: Ready
- Added alert when you login and register
- Changed profile location in navbar
Related issues: Closes #206 Closes #107
> RFR: login alert

- backend/api/views/authenticate.py
:construction: In development
changed username already exists
Related issues: closes #217
> WIP: changed username already taken message

- frontend/src/components/QuizRedo.js
- frontend/src/components/QuizViewer.js
- frontend/src/pages/QuizPage.js
- frontend/src/styles/QuizPage.scss
:rocket: Ready
1. make a progress bar to show quiz completion progress
2. make redo button next to progress bar
3. show final results as a progress  bar in redo modal
4. remove finish attempt and move functionality to "last" submit
*last as in the last question actually answered, not the last question in the list
Related issues: closes #156 
> RFR: Quiz Progress

- frontend/src/components/SearchResults.js
:rocket: Ready
Grade filter removes all books from search results
Related issues: #66 
> RFR: fixed parseInt for grade filter

- backend/api/views/book.py
:rocket: Ready
Added published to edit book route
Related issues: #222
> RFR: Added publish to book edit

- frontend/src/components/CatalogCardBook.js
- frontend/src/components/RedirectingSearchBar.js
- frontend/src/pages/Home.js
- frontend/src/pages/ReadingOlympics/ROHome.js
- frontend/src/styles/Home.scss
:rocket: Ready
Made book cards on the Reading Olympics Book view pages clickable.
Also removed unnecessary exercise card component from Home page.
Related issues: #70 
> RFR: Clickable Book Card

- frontend/src/components/AdminBookForm.js
- frontend/src/components/AdminBookSelect.js
- frontend/src/components/AdminQuizForm.js
- frontend/src/components/AdminQuizSelect.js
- frontend/src/components/Advice.js
- frontend/src/components/QuizViewer.js
- frontend/src/components/admin/AdminYearSection.js
- frontend/src/pages/About.js
- frontend/src/pages/BadgesPage.js
- frontend/src/pages/Home.js
- frontend/src/pages/ReadingOlympics/ROHome.js
- frontend/src/pages/ReadingOlympics/RORedirectToCurrent.js
- frontend/src/pages/admin/AdminEditBookPage.js
- frontend/src/pages/admin/AdminManageUsersPage.js
- frontend/src/pages/admin/AdminSettingsPage.js
- frontend/src/pages/protection/AdminProtection.js
- frontend/src/pages/protection/AuthenticatedProtection.js
:rocket: Ready
Description is whatever my commits are
> RFR: Cleanup

- backend/api/models/Badge.py
- frontend/src/pages/BadgesPage.js
- frontend/src/styles/BadgesPage.scss
:rocket: Ready
Added labels to badges that are received from the backend
Related issues: #122
> RFR: added badge labels

- backend/api/__init__.py
- backend/api/core.py
- backend/api/models/Year.py
- backend/api/models/__init__.py
- backend/api/views/year.py
:rocket: Ready
See issue
Related issues: closes #215
> RFR: Started work on GET /year

- backend/api/views/authenticate.py
:rocket: Ready
Fixed a small issue where an invalid password would yield the message 'Username not found'
Related issues: #122
> RFR: Better Authentication BE Message

- docs/api_docs.md
- docs/architecture.md
- docs/local_setup.md
- docs/scripts.md
:rocket: Ready
Adding docs detailing architecture, api endpoints, and local setup
> RFR: Added simple docs

- README.md
:rocket: Ready
Changing the readme to reflect more information about the project closes #235
> RFR: Update README.md

- frontend/src/components/BookInfo.js
- frontend/src/components/CatalogCardBook.js
- frontend/src/pages/QuizPage.js
- frontend/src/styles/BookInfo.scss
- frontend/src/styles/QuizPage.scss
- frontend/src/styles/ReadingOlympics.scss
🚧 
Various commits to fix things in #122. 
Related issues: #<number>
> RFR: Various style edits

- backend/api/views/book.py
- frontend/src/pages/admin/AdminCSVUploadPage.js
- frontend/src/utils/api.js
🚀 
Adds the frontend functionality to upload a CSV. This will POST the data to the backend properly, however there is an issue with the backend not parsing the data (seems like there's something going on with invoking `next` on the CSV stream). Hence, it displays that the book has been uploaded successfully but there is no change in the db.
Related issues: #158
Backend fix
> RFR: Added CSV upload functionality (needs backend fix)

- backend/api/models/ParentAdvice.py
- backend/api/views/parentadvice.py
- backend/api/views/year.py
- backend/create_dummy_data.py
- frontend/src/App.js
- frontend/src/components/AdminBookSelect.js
- frontend/src/components/AdminDeleteModal.js
- frontend/src/components/AdminNavigator.js
- frontend/src/components/admin/AdminAdviceForm.js
- frontend/src/components/admin/AdminAdviceSelect.js
- frontend/src/components/admin/AdminYearSection.js
- frontend/src/pages/ParentsPage.js
- frontend/src/pages/ReadingOlympics/RORedirectToCurrent.js
- frontend/src/pages/admin/AdminAddAdvicePage.js
- frontend/src/pages/admin/AdminEditAdvicePage.js
- frontend/src/styles/admin/AdminAdviceForm.scss
- frontend/src/utils/api.js
:rocket: Ready
Add & Edit/Delete pages for parent advice
+ Catch regarding active RO year 
+ Some random typo/copy pasta fixes
Related issues: #237 #122
> Admin pages for Advice

- frontend/src/components/Login.js
- frontend/src/components/Logout.js
- frontend/src/components/Register.js
- frontend/src/pages/protection/AdminProtection.js
- frontend/src/pages/protection/AuthenticatedProtection.js
:rocket: Ready
Before: Only checks that token exists
After: Makes a BE request to ensure token is valid
> RFR: Add auth protection that validates token

- docs/architecture.md
> RFR: Update architecture deployment instructions

- frontend/src/components/Advice.js
- frontend/src/pages/AdvicePage.js
- frontend/src/pages/admin/AdminEditAdvicePage.js
> Fix advice

- frontend/src/pages/account/AccountManagePage.js
- frontend/src/styles/AccountManagePage.scss
> Style account settings page

- .env
- .gitignore
- Pipfile
- Pipfile.lock
- backend/.dockerignore
- backend/Dockerfile
- backend/docker_script.sh
- contributing.md
- docker-compose-dev.yml
- frontend/Dockerfile.dev
To run the project from the main directory run:
`docker-compose -f docker-compose-dev.yml up --build`
This PR makes it a bit easier to start up all services synchronously. The current `docker-compose-dev.yml` makes use of dev environments like React dev server for hot reloading/other benefits and a pipenv environment for the backend. These will need to be changed and optimized for production.
For the React side this will involve an nginx container to replace the react dev server, but I'm not too sure out about the backend yet.
The .env file is included for ease, but of course these will need to be changed for production as well.
We'll also want to coordinate how we handle #253 with this new dev environment in mind. However we choose to seed the db will have to take into account 
Related …
> Improve local development

- .gitignore
- backend/docker_script.sh
- docker-compose-dev.yml
- testdb_seed
* added to .gitignore
* added a file testdb_seed
* load testdb_seed in docker-compose-dev
* removed reseting db from docker_script because this is handled in docker-compose-dev
NOTE:
docker-compose.yml is not currently used and will not reset or seed the database.
Just use docker-compose-dev.yml for now.
postgres port was changed from 5432 to 5431 to avoid a conflict on my local dev env. If this creates other conflicts we can switch it back to 5432.
Related issues: #<number>
> Use Docker to seed db (#253)

- frontend/package-lock.json
- frontend/src/components/Advice.js
- frontend/src/components/PReadsNavbar.js
- frontend/src/pages/AdvicePage.js
- frontend/src/pages/BookPage.js
- frontend/src/pages/Home.js
- frontend/src/pages/ReadingOlympics/ROHome.js
- frontend/src/pages/admin/AdminAddAdvicePage.js
- frontend/src/pages/admin/AdminAddBookPage.js
- frontend/src/pages/admin/AdminAddQuizPage.js
- frontend/src/pages/admin/AdminEditAdvicePage.js
- frontend/src/pages/admin/AdminEditBookPage.js
- frontend/src/pages/admin/AdminEditQuizPage.js
The purpose of this PR is change reactstrap NavLink components and anchor tags to react-router Link components throughout the app.
Related issues: Closes #258
> Use React Router Links throughout the App #258

- frontend/src/pages/BookPage.js
:rocket: Ready
I must have missed this when fixing merge conflicts on a different PR.
> add Link import

- frontend/src/components/PReadsNavbar.js
- frontend/src/components/account/Login.js
- frontend/src/components/account/Register.js
- frontend/src/pages/AdvicePage.js
- frontend/src/pages/BookPage.js
- frontend/src/pages/QuizPage.js
- frontend/src/pages/ReadingOlympics/RORedirectToCurrent.js
- frontend/src/pages/account/AccountManagePage.js
:rocket: Ready
The purpose of this PR is to add error handling for user facing pages
Related issues: Closes #254
> Error Handling #254

- frontend/src/components/account/Login.js
- frontend/src/styles/Login.scss
- updated local state to include 'loading'
- conditionally render loading div or just "Login" string on the login
button
- add styles for spinner in plain css
:rocket: Ready
Done in plain css because bootstrap 4.3 has some built in spinner classes so we could avoid the custom css here, but we are only on 4.1. I didn't have time to look into the upgrade but it shouldn't be too bad considering it is a minor upgrade.
Related issues: #257 
Example with Crome network throttling set to 'Slow 3G'
> Add loading state to log in button

- docker-compose.yml
- frontend/Dockerfile
- frontend/philareads.conf
:partyparrot:
:rocket: Ready
Adds a build step to the frontend and adds `docker-compose.yml` to use the new dockerfile
Related issues: #289
> add docker production compose

- frontend/src/components/PReadsNavbar.js
- frontend/src/components/catalog/CatalogCardBook.js
- frontend/src/styles/ReadingOlympics.scss
Related Issues:
https://github.com/hack4impact-uiuc/philareads/issues/296
https://github.com/hack4impact-uiuc/philareads/issues/148
Current PR
> fixes for issues 296 and 148
